apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels: 
    name: frontend-service
    app: guestbook-app
spec:
  type: LoadBalancer
  selector:
    name: frontend-pod
    app: guestbook-app
  ports:
  - port: 80
    targetPort: 80
